<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8" />
		<meta name="author" content="Newnorth Technology" />
		<meta name="generator" content="Newnorth PHP Framework" />
		<title>Newnorth Alerts</title>
		<link href="/css/defaults.css" rel="stylesheet" type="text/css" />
		<link href="/css/page.css" rel="stylesheet" type="text/css" />
		<link href="/css/page_overview.css" rel="stylesheet" type="text/css" />
		<script src="/js/Newnorth.js" type="text/javascript"></script>
		<script src="/js/page.js" type="text/javascript"></script>
		<script src="/js/page_overview.js" type="text/javascript"></script>
		<script src="/js/page_overview_wall.js" type="text/javascript"></script>
		<script src="/js/page_overview_wall_test.js" type="text/javascript"></script>
		<script src="/js/page_overview_upcommingevents.js" type="text/javascript"></script>
		<script src="/js/page_overview_upcommingevents_test.js" type="text/javascript"></script>
	</head>
	<body>
		<header id="MainMenu">
			<div class="Left"></div>
			<div class="Link"><div><div class="Text"><b>Overview</b><br /><span>Warnings&nbsp;&amp; processes</span></div><div class="Count">12</div></div></div>
			<a class="Link" href="javascript:void(0);"><div><div class="Text"><b>Tests</b><br /><span>Details&nbsp;on all&nbsp;tests</span></div><div class="Count">1355</div></div></a>
			<a class="Link" href="javascript:void(0);"><div><div class="Text"><b>Scheduled tasks</b><br /><span>Details&nbsp;on all&nbsp;scheduled&nbsp;tasks</span></div><div class="Count">124</div></div></a>
			<a class="Link" href="javascript:void(0);"><div><div class="Text"><b>Log</b><br /><span>Records&nbsp;of past&nbsp;occurrences</span></div><div class="Count">12</div></div></a>
			<div class="Right"></div>
		</header>
		<div id="Overview" class="Page">
			<h1>Overview</h1>
			<div class="Content">
				<div>
					<h2>Warnings</h2>
					<div id="Wall"></div>
				</div>
				<div>
					<h2>Processes</h2>
					<div id="UpcommingEvents"></div>
				</div>
			</div>
		</div>
	</body>
</html>